# Generated by Django 3.0.2 on 2020-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
